geometry_msgs/Pose goal  #stores the position and orientation of base link frame of the system
uint8 HOME = 0     #enum for home coordinates as goal, the home cooridinates could either be passes in goal or accessed from local data in the mobile base node
uint8 CRATE =1   #enum for Crate Coordinates as goal, expects goal to be filled
uint8 HORIZONTAL =2 #enum for only horizontal goal i.e x cooridinate goal, expects goal to be passed but process only the x coordinate
uint8 VERTICAL =2 #enum for only Vertical goal i.e z coordinate goal. expects goal to be passed but processes only z coorindate
uint8 GENERAL =3 #enum for any other genral pose goal, expects goal to be passed
uint8 goal_type   #to indicated the goal type
---
bool bsuccess #returns true acknoledgment if goal reached successfully else false
string message  #relevant message along with acknowlegdement