sensor_msgs/Image image_to_be_infered





---
bool bsuccess
sensor_msgs/Image merged_masks_image
sensor_msgs/Image infered_image

# a list of mask_indexs msg where each element is a list of index points that belong to a mask
MaskCoords[] list_mask_coords
MaskCoords[] picking_points


